### ISSUE TITLE
Issue in your code is you have not made me contributor

### ISSUE THREAD

**Issue by Vedant0616** [Dhairya44/CarParking#1]

**Comment by p3Xxer** [comment]
This is a reputed project.
Only certified developers are allowed to contribute.
Please don't disrupt the working of the project with your useless comments or we will be forced to take necessary actions.

**Comment by Vedant0616** [comment]
I am acknowledging your previous comment. 
I want to say that I am a certified developer. 
I am given the certification for the best copy paster of the websites from the hidden corners of internet.
